//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCFileService
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderfile
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string Grade { get; set; }
        public string Flute { get; set; }
        public string Test { get; set; }
        public string DueDate { get; set; }
        public string Width { get; set; }
        public string Length { get; set; }
        public string Quantity { get; set; }
        public string MaxOver { get; set; }
        public string MaxUnder { get; set; }
        public string Boardcode { get; set; }
        public string ShipToName { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToZip { get; set; }
        public string ShipToCode { get; set; }
        public string CustomerPO { get; set; }
        public string CustomerPOLine { get; set; }
        public string ClientItem { get; set; }
        public string LoadTag { get; set; }
        public string FirstMachineCode { get; set; }
        public string PiecesPerPallet { get; set; }
        public string FanFold { get; set; }
        public string FanFoldSheetLength { get; set; }
        public string FanFoldUnitHeight { get; set; }
        public string FanFoldPerforationLength { get; set; }
        public string CSCOrderID { get; set; }
        public string DoNotUpgrade { get; set; }
        public string TagPerUnit { get; set; }
        public string AdhesiveCode { get; set; }
        public string EOL { get; set; }
    }
}
