//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCFileService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SpecialInstruction
    {
        [Key]
        public int ID { get; set; }
        public int orderfileID { get; set; }
        public string Type { get; set; }
        public string SpecialInstruction1 { get; set; }
        public string SpecialInstruction2 { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string ThreePLRefNo { get; set; }
        public string EOL { get; set; }
    }
}
